name: template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^3.0.7

dev_dependencies:
  dart_code_metrics: ^4.14.0
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans/NotoSans-Black.ttf
        - asset: assets/fonts/noto_sans/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/noto_sans/NotoSans-Bold.ttf
        - asset: assets/fonts/noto_sans/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/noto_sans/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/noto_sans/NotoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/noto_sans/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/noto_sans/NotoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/noto_sans/NotoSans-Italic.ttf
        - asset: assets/fonts/noto_sans/NotoSans-Light.ttf
        - asset: assets/fonts/noto_sans/NotoSans-LightItalic.ttf
        - asset: assets/fonts/noto_sans/NotoSans-Medium.ttf
        - asset: assets/fonts/noto_sans/NotoSans-MediumItalic.ttf
        - asset: assets/fonts/noto_sans/NotoSans-Regular.ttf
        - asset: assets/fonts/noto_sans/NotoSans-SemiBold.ttf
        - asset: assets/fonts/noto_sans/NotoSans-SemiBoldItalic.ttf
        - asset: assets/fonts/noto_sans/NotoSans-Thin.ttf
        - asset: assets/fonts/noto_sans/NotoSans-ThinItalic.ttf

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#3558CD"
  image: assets/img/img_splash_screen_logo.png
  fullscreen: true
